#!/bin/sh

# udev stuff

echo "Setting User Permissions for USB port for EXPEYES: AVR, FT232 and MCP2200"
install -m 644 99-phoenix.rules /lib/udev/rules.d
/etc/init.d/udev restart
echo "Reconnect EXEYES on USB Port for permissions to take effect"

# man database stuff

echo -n Updating the manpages... 
mandb -q
echo Done.