// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Sun Aug  9 15:29:58 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MICROHOPE_H
#define MICROHOPE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxPanel* panel_1;
    wxMenuBar* Microhope_menubar;
    wxToolBar* Microhope_toolbar;
    wxStatusBar* Microhope_statusbar;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void ---(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MICROHOPE_H
