# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advancedLogger.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.centralwidget)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout.addWidget(self.xLabel, 2, 1, 1, 1)
        self.yLabel = QtWidgets.QLabel(self.centralwidget)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout.addWidget(self.yLabel, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 8, 0, 1, 1)
        self.settlingTimeBox = QtWidgets.QSpinBox(self.frame_2)
        self.settlingTimeBox.setMaximum(10000)
        self.settlingTimeBox.setProperty("value", 2)
        self.settlingTimeBox.setObjectName("settlingTimeBox")
        self.gridLayout_2.addWidget(self.settlingTimeBox, 7, 1, 1, 1)
        self.logBox = QtWidgets.QCheckBox(self.frame_2)
        self.logBox.setObjectName("logBox")
        self.gridLayout_2.addWidget(self.logBox, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.datapointsBox = QtWidgets.QSpinBox(self.frame_2)
        self.datapointsBox.setMinimum(5)
        self.datapointsBox.setMaximum(20000)
        self.datapointsBox.setProperty("value", 50)
        self.datapointsBox.setObjectName("datapointsBox")
        self.gridLayout_2.addWidget(self.datapointsBox, 8, 1, 1, 1)
        self.delayBox = QtWidgets.QSpinBox(self.frame_2)
        self.delayBox.setMaximum(20000)
        self.delayBox.setProperty("value", 50)
        self.delayBox.setObjectName("delayBox")
        self.gridLayout_2.addWidget(self.delayBox, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.plot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setObjectName("plot")
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.setX)
        self.pushButton_2.clicked.connect(MainWindow.setY)
        self.logBox.toggled['bool'].connect(MainWindow.setRecord)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "CHOOSE Y PARAMETER"))
        self.xLabel.setText(_translate("MainWindow", "Click the Button above to select X axis parameter"))
        self.yLabel.setText(_translate("MainWindow", "Click the Button above to select Y axis parameter"))
        self.pushButton.setText(_translate("MainWindow", "CHOOSE X PARAMETER"))
        self.label_7.setText(_translate("MainWindow", "Datapoints"))
        self.settlingTimeBox.setSuffix(_translate("MainWindow", " milliSeconds"))
        self.logBox.setText(_translate("MainWindow", "LOG DATA"))
        self.label_6.setText(_translate("MainWindow", "Time Interval"))
        self.delayBox.setSuffix(_translate("MainWindow", " milliSeconds"))
        self.label_8.setText(_translate("MainWindow", "Settling Time b/w X and Y"))

from pyqtgraph import PlotWidget
