# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newtonslaws.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.splineBox = QtWidgets.QComboBox(self.centralwidget)
        self.splineBox.setObjectName("splineBox")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.splineBox.addItem("")
        self.gridLayout.addWidget(self.splineBox, 0, 4, 1, 1)
        self.recordBox = QtWidgets.QCheckBox(self.centralwidget)
        self.recordBox.setChecked(True)
        self.recordBox.setObjectName("recordBox")
        self.gridLayout.addWidget(self.recordBox, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(138, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1)
        self.samplesBox = QtWidgets.QComboBox(self.centralwidget)
        self.samplesBox.setObjectName("samplesBox")
        self.gridLayout.addWidget(self.samplesBox, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 7, 1, 1)
        self.polyBox = QtWidgets.QComboBox(self.centralwidget)
        self.polyBox.setObjectName("polyBox")
        self.gridLayout.addWidget(self.polyBox, 0, 8, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphPosition = PlotWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphPosition.sizePolicy().hasHeightForWidth())
        self.graphPosition.setSizePolicy(sizePolicy)
        self.graphPosition.setObjectName("graphPosition")
        self.horizontalLayout.addWidget(self.graphPosition)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gaugeLayout = QtWidgets.QVBoxLayout(self.frame)
        self.gaugeLayout.setContentsMargins(0, 0, 0, 0)
        self.gaugeLayout.setSpacing(0)
        self.gaugeLayout.setObjectName("gaugeLayout")
        self.horizontalLayout.addWidget(self.frame)
        self.graphResults = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphResults.sizePolicy().hasHeightForWidth())
        self.graphResults.setSizePolicy(sizePolicy)
        self.graphResults.setObjectName("graphResults")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 9)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.recordBox.clicked['bool'].connect(MainWindow.setRecord)
        self.pushButton_2.clicked.connect(MainWindow.analysis)
        self.samplesBox.currentIndexChanged['QString'].connect(MainWindow.redoAnalysis)
        self.polyBox.currentIndexChanged['QString'].connect(MainWindow.redoAnalysis)
        self.splineBox.currentIndexChanged['QString'].connect(MainWindow.redoAnalysis)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.splineBox.setItemText(0, _translate("MainWindow", "None"))
        self.splineBox.setItemText(1, _translate("MainWindow", "2"))
        self.splineBox.setItemText(2, _translate("MainWindow", "3"))
        self.splineBox.setItemText(3, _translate("MainWindow", "4"))
        self.splineBox.setItemText(4, _translate("MainWindow", "5"))
        self.splineBox.setItemText(5, _translate("MainWindow", "6"))
        self.splineBox.setItemText(6, _translate("MainWindow", "7"))
        self.splineBox.setItemText(7, _translate("MainWindow", "8"))
        self.splineBox.setItemText(8, _translate("MainWindow", "9"))
        self.splineBox.setItemText(9, _translate("MainWindow", "10"))
        self.recordBox.setText(_translate("MainWindow", "RECORD"))
        self.pushButton_2.setText(_translate("MainWindow", "Calculate"))
        self.label.setText(_translate("MainWindow", "Averaging Samples"))
        self.samplesBox.setToolTip(_translate("MainWindow", "Number of samples considered for moving average in results calculation"))
        self.label_2.setText(_translate("MainWindow", "Polynomial Degree"))
        self.polyBox.setToolTip(_translate("MainWindow", "Degree of the polynomial used for smoothing the data"))
        self.label_3.setText(_translate("MainWindow", "Spline"))

from pyqtgraph import PlotWidget
